-- MySQL Script generated by MySQL Workbench
-- Sun Dec 31 14:24:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tow` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tow` (
  `tow_kod` VARCHAR(45) NOT NULL,
  `tow_name` VARCHAR(45) NULL,
  `ilo_is` DOUBLE NULL,
  `ce` DOUBLE NULL,
  PRIMARY KEY (`tow_kod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`odb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`odb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`odb` (
  `kod_odb` INT NOT NULL,
  `name_odb` VARCHAR(45) NULL,
  `nip` BIGINT(15) NULL,
  PRIMARY KEY (`kod_odb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wz` (
  `idwz` INT NOT NULL AUTO_INCREMENT,
  `val` DOUBLE NULL,
  `odb_kod_odb` INT NOT NULL,
  `dok_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idwz`),
  INDEX `fk_wz_odb1_idx` (`odb_kod_odb` ASC) VISIBLE,
  CONSTRAINT `fk_wz_odb1`
    FOREIGN KEY (`odb_kod_odb`)
    REFERENCES `mydb`.`odb` (`kod_odb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wz_p`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wz_p` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wz_p` (
  `idwz_p` INT NOT NULL AUTO_INCREMENT,
  `ilo` INT NULL,
  `val` DOUBLE NULL,
  `tow_tow_kod` VARCHAR(45) NOT NULL,
  `wz_idwz` INT NOT NULL,
  PRIMARY KEY (`idwz_p`),
  INDEX `fk_wz_p_tow1_idx` (`tow_tow_kod` ASC) VISIBLE,
  INDEX `fk_wz_p_wz1_idx` (`wz_idwz` ASC) VISIBLE,
  CONSTRAINT `fk_wz_p_tow1`
    FOREIGN KEY (`tow_tow_kod`)
    REFERENCES `mydb`.`tow` (`tow_kod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wz_p_wz1`
    FOREIGN KEY (`wz_idwz`)
    REFERENCES `mydb`.`wz` (`idwz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dst` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dst` (
  `kod_dst` INT NOT NULL,
  `name_dst` VARCHAR(45) NULL,
  `nip` BIGINT(15) NULL,
  PRIMARY KEY (`kod_dst`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pz` (
  `idpz` INT NOT NULL AUTO_INCREMENT,
  `val` DOUBLE NULL,
  `dst_kod_dst` INT NOT NULL,
  `dok_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idpz`),
  INDEX `fk_pz_dst1_idx` (`dst_kod_dst` ASC) VISIBLE,
  CONSTRAINT `fk_pz_dst1`
    FOREIGN KEY (`dst_kod_dst`)
    REFERENCES `mydb`.`dst` (`kod_dst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pz_p`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pz_p` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pz_p` (
  `idpz_p` INT NOT NULL AUTO_INCREMENT,
  `ilo` INT NULL,
  `val` DOUBLE NULL,
  `pz_idpz` INT NOT NULL,
  `tow_tow_kod` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpz_p`),
  INDEX `fk_pz_p_pz1_idx` (`pz_idpz` ASC) VISIBLE,
  INDEX `fk_pz_p_tow1_idx` (`tow_tow_kod` ASC) VISIBLE,
  CONSTRAINT `fk_pz_p_pz1`
    FOREIGN KEY (`pz_idpz`)
    REFERENCES `mydb`.`pz` (`idpz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pz_p_tow1`
    FOREIGN KEY (`tow_tow_kod`)
    REFERENCES `mydb`.`tow` (`tow_kod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
